language: go

go:
  - 1.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x

env:
  - GO111MODULE=on

install: true

script:
  - go test ./...

after_success:
  - go test -coverprofile=coverage.txt -covermode=atomic ./...
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - go get github.com/mitchellh/gox
  - if [ "$(echo $TRAVIS_TAG | cut -d '-' -f 2 | cut -d '.' -f 1)" = "pr" ]; then
      make build-pre-release;
    else
      make build-all;
    fi
  - make dist

deploy:
  - provider: releases
    api_key: $GITHUB_API_TOKEN
    skip_cleanup: true
    overwrite: true
    file_glob: true
    file: 'dist/*.tar.gz'
    prerelease: false
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
      go: '1.x'
  - provider: releases
    api_key: $GITHUB_API_TOKEN
    skip_cleanup: true
    overwrite: true
    file_glob: true
    file: 'dist/*.tar.gz'
    prerelease: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+\-pr\.[0-9]+$
      go: '1.x'
